# Generated by Django 4.2.1 on 2023-05-13 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_profile_otp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['otp']},
        ),
    ]
